// Code generated by cmd/generate_tests. DO NOT EDIT.
//
// Source: github.com/dcastil/tailwind-merge tests/*.test.ts

package twmerge

import "testing"

// From arbitrary-properties.test.ts
func TestGenerated_ArbitraryProperties(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "handles arbitrary property conflicts correctly", in: "[paint-order:markers] [paint-order:normal]", out: "[paint-order:normal]"},
		{desc: "handles arbitrary property conflicts with modifiers correctly", in: "[paint-order:markers] hover:[paint-order:normal]", out: "[paint-order:markers] hover:[paint-order:normal]"},
		{desc: "handles arbitrary property conflicts with modifiers correctly", in: "hover:[paint-order:markers] hover:[paint-order:normal]", out: "hover:[paint-order:normal]"},
		{desc: "handles arbitrary property conflicts with modifiers correctly", in: "hover:focus:[paint-order:markers] focus:hover:[paint-order:normal]", out: "focus:hover:[paint-order:normal]"},
		{desc: "handles important modifier correctly", in: "![some:prop] [some:other]", out: "![some:prop] [some:other]"},
		{desc: "handles important modifier correctly", in: "![some:prop] [some:other] [some:one] ![some:another]", out: "[some:one] ![some:another]"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From arbitrary-values.test.ts
func TestGenerated_ArbitraryValues(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "handles complex arbitrary value conflicts correctly", in: "grid-rows-[1fr,auto] grid-rows-2", out: "grid-rows-2"},
		{desc: "handles complex arbitrary value conflicts correctly", in: "grid-rows-[repeat(20,minmax(0,1fr))] grid-rows-3", out: "grid-rows-3"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "m-[2px] m-[10px]", out: "m-[10px]"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "my-[2px] m-[10rem]", out: "m-[10rem]"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "cursor-pointer cursor-[grab]", out: "cursor-[grab]"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "opacity-10 opacity-[0.025]", out: "opacity-[0.025]"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "scale-75 scale-[1.7]", out: "scale-[1.7]"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "brightness-90 brightness-[1.75]", out: "brightness-[1.75]"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "min-h-[0.5px] min-h-[0]", out: "min-h-[0]"},
		{desc: "handles simple conflicts with arbitrary values correctly", in: "text-[0.5px] text-[color:0]", out: "text-[0.5px] text-[color:0]"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From arbitrary-variants.test.ts
func TestGenerated_ArbitraryVariants(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "arbitrary variants with arbitrary properties", in: "[&>*]:[color:red] [&>*]:[color:blue]", out: "[&>*]:[color:blue]"},
		{desc: "arbitrary variants with attribute selectors", in: "[&[data-open]]:underline [&[data-open]]:line-through", out: "[&[data-open]]:line-through"},
		{desc: "arbitrary variants with modifiers", in: "dark:lg:hover:[&>*]:underline dark:lg:hover:[&>*]:line-through", out: "dark:lg:hover:[&>*]:line-through"},
		{desc: "arbitrary variants with modifiers", in: "dark:lg:hover:[&>*]:underline dark:hover:lg:[&>*]:line-through", out: "dark:hover:lg:[&>*]:line-through"},
		{desc: "arbitrary variants with modifiers", in: "hover:[&>*]:underline [&>*]:hover:line-through", out: "hover:[&>*]:underline [&>*]:hover:line-through"},
		{desc: "basic arbitrary variants", in: "[p]:underline [p]:line-through", out: "[p]:line-through"},
		{desc: "basic arbitrary variants", in: "[&>*]:underline [&>*]:line-through", out: "[&>*]:line-through"},
		{desc: "basic arbitrary variants", in: "[&>*]:underline [&>*]:line-through [&_div]:line-through", out: "[&>*]:line-through [&_div]:line-through"},
		{desc: "basic arbitrary variants", in: "supports-[display:grid]:flex supports-[display:grid]:grid", out: "supports-[display:grid]:grid"},
		{desc: "multiple arbitrary variants", in: "[&>*]:[&_div]:underline [&>*]:[&_div]:line-through", out: "[&>*]:[&_div]:line-through"},
		{desc: "multiple arbitrary variants", in: "[&>*]:[&_div]:underline [&_div]:[&>*]:line-through", out: "[&>*]:[&_div]:underline [&_div]:[&>*]:line-through"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From class-group-conflicts.test.ts
func TestGenerated_ClassGroupConflicts(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "merges classes from Font Variant Numeric section correctly", in: "lining-nums tabular-nums diagonal-fractions", out: "lining-nums tabular-nums diagonal-fractions"},
		{desc: "merges classes from Font Variant Numeric section correctly", in: "normal-nums tabular-nums diagonal-fractions", out: "tabular-nums diagonal-fractions"},
		{desc: "merges classes from Font Variant Numeric section correctly", in: "tabular-nums diagonal-fractions normal-nums", out: "normal-nums"},
		{desc: "merges classes from Font Variant Numeric section correctly", in: "tabular-nums proportional-nums", out: "proportional-nums"},
		{desc: "merges classes from same group correctly", in: "overflow-x-auto overflow-x-hidden", out: "overflow-x-hidden"},
		{desc: "merges classes from same group correctly", in: "basis-full basis-auto", out: "basis-auto"},
		{desc: "merges classes from same group correctly", in: "w-full w-fit", out: "w-fit"},
		{desc: "merges classes from same group correctly", in: "overflow-x-auto overflow-x-hidden overflow-x-scroll", out: "overflow-x-scroll"},
		{desc: "merges classes from same group correctly", in: "overflow-x-auto hover:overflow-x-hidden overflow-x-scroll", out: "hover:overflow-x-hidden overflow-x-scroll"},
		{desc: "merges classes from same group correctly", in: "gap-2 gap-px basis-px basis-3", out: "gap-px basis-3"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From colors.test.ts
func TestGenerated_Colors(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "handles color conflicts properly", in: "bg-grey-5 bg-hotpink", out: "bg-hotpink"},
		{desc: "handles color conflicts properly", in: "hover:bg-grey-5 hover:bg-hotpink", out: "hover:bg-hotpink"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From conflicts-across-class-groups.test.ts
func TestGenerated_ConflictsAcrossClassGroups(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "handles conflicts across class groups correctly", in: "inset-1 inset-x-1", out: "inset-1 inset-x-1"},
		{desc: "handles conflicts across class groups correctly", in: "inset-x-1 inset-1", out: "inset-1"},
		{desc: "handles conflicts across class groups correctly", in: "inset-x-1 left-1 inset-1", out: "inset-1"},
		{desc: "handles conflicts across class groups correctly", in: "inset-x-1 inset-1 left-1", out: "inset-1 left-1"},
		{desc: "handles conflicts across class groups correctly", in: "inset-x-1 right-1 inset-1", out: "inset-1"},
		{desc: "handles conflicts across class groups correctly", in: "inset-x-1 right-1 inset-x-1", out: "inset-x-1"},
		{desc: "handles conflicts across class groups correctly", in: "inset-x-1 right-1 inset-y-1", out: "inset-x-1 right-1 inset-y-1"},
		{desc: "handles conflicts across class groups correctly", in: "right-1 inset-x-1 inset-y-1", out: "inset-x-1 inset-y-1"},
		{desc: "handles conflicts across class groups correctly", in: "inset-x-1 hover:left-1 inset-1", out: "hover:left-1 inset-1"},
		{desc: "line-clamp classes do create conflicts correctly", in: "overflow-auto inline line-clamp-1", out: "line-clamp-1"},
		{desc: "line-clamp classes do create conflicts correctly", in: "line-clamp-1 overflow-auto inline", out: "line-clamp-1 overflow-auto inline"},
		{desc: "ring and shadow classes do not create conflict", in: "ring shadow", out: "ring shadow"},
		{desc: "ring and shadow classes do not create conflict", in: "ring-2 shadow-md", out: "ring-2 shadow-md"},
		{desc: "ring and shadow classes do not create conflict", in: "shadow ring", out: "shadow ring"},
		{desc: "ring and shadow classes do not create conflict", in: "shadow-md ring-2", out: "shadow-md ring-2"},
		{desc: "touch classes do create conflicts correctly", in: "touch-pan-x touch-pan-right", out: "touch-pan-right"},
		{desc: "touch classes do create conflicts correctly", in: "touch-none touch-pan-x", out: "touch-pan-x"},
		{desc: "touch classes do create conflicts correctly", in: "touch-pan-x touch-none", out: "touch-none"},
		{desc: "touch classes do create conflicts correctly", in: "touch-pan-x touch-pan-y touch-pinch-zoom", out: "touch-pan-x touch-pan-y touch-pinch-zoom"},
		{desc: "touch classes do create conflicts correctly", in: "touch-manipulation touch-pan-x touch-pan-y touch-pinch-zoom", out: "touch-pan-x touch-pan-y touch-pinch-zoom"},
		{desc: "touch classes do create conflicts correctly", in: "touch-pan-x touch-pan-y touch-pinch-zoom touch-auto", out: "touch-auto"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From important-modifier.test.ts
func TestGenerated_ImportantModifier(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "merges tailwind classes with important modifier correctly", in: "font-medium! font-bold!", out: "font-bold!"},
		{desc: "merges tailwind classes with important modifier correctly", in: "font-medium! font-bold! font-thin", out: "font-bold! font-thin"},
		{desc: "merges tailwind classes with important modifier correctly", in: "right-2! -inset-x-px!", out: "-inset-x-px!"},
		{desc: "merges tailwind classes with important modifier correctly", in: "focus:inline! focus:block!", out: "focus:block!"},
		{desc: "merges tailwind classes with important modifier correctly", in: "[--my-var:20px]! [--my-var:30px]!", out: "[--my-var:30px]!"},
		{desc: "merges tailwind classes with important modifier correctly", in: "font-medium! !font-bold", out: "!font-bold"},
		{desc: "merges tailwind classes with important modifier correctly", in: "!font-medium !font-bold", out: "!font-bold"},
		{desc: "merges tailwind classes with important modifier correctly", in: "!font-medium !font-bold font-thin", out: "!font-bold font-thin"},
		{desc: "merges tailwind classes with important modifier correctly", in: "!right-2 !-inset-x-px", out: "!-inset-x-px"},
		{desc: "merges tailwind classes with important modifier correctly", in: "focus:!inline focus:!block", out: "focus:!block"},
		{desc: "merges tailwind classes with important modifier correctly", in: "![--my-var:20px] ![--my-var:30px]", out: "![--my-var:30px]"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From modifiers.test.ts
func TestGenerated_Modifiers(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "conflicts across prefix modifiers", in: "hover:block hover:inline", out: "hover:inline"},
		{desc: "conflicts across prefix modifiers", in: "hover:block hover:focus:inline", out: "hover:block hover:focus:inline"},
		{desc: "conflicts across prefix modifiers", in: "hover:block hover:focus:inline focus:hover:inline", out: "hover:block focus:hover:inline"},
		{desc: "conflicts across prefix modifiers", in: "focus-within:inline focus-within:block", out: "focus-within:block"},
		{desc: "sorts modifiers correctly", in: "c:d:e:block d:c:e:inline", out: "d:c:e:inline"},
		{desc: "sorts modifiers correctly", in: "*:before:block *:before:inline", out: "*:before:inline"},
		{desc: "sorts modifiers correctly", in: "*:before:block before:*:inline", out: "*:before:block before:*:inline"},
		{desc: "sorts modifiers correctly", in: "x:y:*:z:block y:x:*:z:inline", out: "y:x:*:z:inline"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From negative-values.test.ts
func TestGenerated_NegativeValues(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "handles conflicts across groups with negative values correctly", in: "-right-1 inset-x-1", out: "inset-x-1"},
		{desc: "handles conflicts across groups with negative values correctly", in: "hover:focus:-right-1 focus:hover:inset-x-1", out: "focus:hover:inset-x-1"},
		{desc: "handles conflicts between positive and negative values correctly", in: "-m-2 m-auto", out: "m-auto"},
		{desc: "handles conflicts between positive and negative values correctly", in: "top-12 -top-69", out: "-top-69"},
		{desc: "handles negative value conflicts correctly", in: "-m-2 -m-5", out: "-m-5"},
		{desc: "handles negative value conflicts correctly", in: "-top-12 -top-2000", out: "-top-2000"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From non-conflicting-classes.test.ts
func TestGenerated_NonConflictingClasses(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "merges non-conflicting classes correctly", in: "border-t border-white/10", out: "border-t border-white/10"},
		{desc: "merges non-conflicting classes correctly", in: "border-t border-white", out: "border-t border-white"},
		{desc: "merges non-conflicting classes correctly", in: "text-3.5xl text-black", out: "text-3.5xl text-black"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From non-tailwind-classes.test.ts
func TestGenerated_NonTailwindClasses(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "does not alter non-tailwind classes", in: "non-tailwind-class inline block", out: "non-tailwind-class block"},
		{desc: "does not alter non-tailwind classes", in: "inline block inline-1", out: "block inline-1"},
		{desc: "does not alter non-tailwind classes", in: "inline block i-inline", out: "block i-inline"},
		{desc: "does not alter non-tailwind classes", in: "focus:inline focus:block focus:inline-1", out: "focus:block focus:inline-1"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From per-side-border-colors.test.ts
func TestGenerated_PerSideBorderColors(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "merges classes with per-side border colors correctly", in: "border-t-some-blue border-t-other-blue", out: "border-t-other-blue"},
		{desc: "merges classes with per-side border colors correctly", in: "border-t-some-blue border-some-blue", out: "border-some-blue"},
		{desc: "merges classes with per-side border colors correctly", in: "border-some-blue border-s-some-blue", out: "border-some-blue border-s-some-blue"},
		{desc: "merges classes with per-side border colors correctly", in: "border-e-some-blue border-some-blue", out: "border-some-blue"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From pseudo-variants.test.ts
func TestGenerated_PseudoVariants(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "handles pseudo variant group conflicts properly", in: "group-empty:p-2 group-empty:p-3", out: "group-empty:p-3"},
		{desc: "handles pseudo variant group conflicts properly", in: "peer-empty:p-2 peer-empty:p-3", out: "peer-empty:p-3"},
		{desc: "handles pseudo variant group conflicts properly", in: "group-empty:p-2 peer-empty:p-3", out: "group-empty:p-2 peer-empty:p-3"},
		{desc: "handles pseudo variant group conflicts properly", in: "hover:group-empty:p-2 hover:group-empty:p-3", out: "hover:group-empty:p-3"},
		{desc: "handles pseudo variant group conflicts properly", in: "group-read-only:p-2 group-read-only:p-3", out: "group-read-only:p-3"},
		{desc: "handles pseudo variants conflicts properly", in: "empty:p-2 empty:p-3", out: "empty:p-3"},
		{desc: "handles pseudo variants conflicts properly", in: "hover:empty:p-2 hover:empty:p-3", out: "hover:empty:p-3"},
		{desc: "handles pseudo variants conflicts properly", in: "read-only:p-2 read-only:p-3", out: "read-only:p-3"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From standalone-classes.test.ts
func TestGenerated_StandaloneClasses(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "merges standalone classes from same group correctly", in: "inline block", out: "block"},
		{desc: "merges standalone classes from same group correctly", in: "hover:block hover:inline", out: "hover:inline"},
		{desc: "merges standalone classes from same group correctly", in: "hover:block hover:block", out: "hover:block"},
		{desc: "merges standalone classes from same group correctly", in: "inline hover:inline focus:inline hover:block hover:focus:block", out: "inline focus:inline hover:block hover:focus:block"},
		{desc: "merges standalone classes from same group correctly", in: "underline line-through", out: "line-through"},
		{desc: "merges standalone classes from same group correctly", in: "line-through no-underline", out: "no-underline"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From tailwind-css-versions.test.ts
func TestGenerated_TailwindCssVersions(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "supports Tailwind CSS v3.3 features", in: "text-red text-lg/7 text-lg/8", out: "text-red text-lg/8"},
		{desc: "supports Tailwind CSS v3.3 features", in: "line-clamp-2 line-clamp-none line-clamp-[10]", out: "line-clamp-[10]"},
		{desc: "supports Tailwind CSS v3.3 features", in: "delay-150 delay-0 duration-150 duration-0", out: "delay-0 duration-0"},
		{desc: "supports Tailwind CSS v3.3 features", in: "justify-normal justify-center justify-stretch", out: "justify-stretch"},
		{desc: "supports Tailwind CSS v3.3 features", in: "content-normal content-center content-stretch", out: "content-stretch"},
		{desc: "supports Tailwind CSS v3.3 features", in: "whitespace-nowrap whitespace-break-spaces", out: "whitespace-break-spaces"},
		{desc: "supports Tailwind CSS v3.4 features", in: "h-svh h-dvh w-svw w-dvw", out: "h-dvh w-dvw"},
		{desc: "supports Tailwind CSS v3.4 features", in: "w-5 h-3 size-10 w-12", out: "size-10 w-12"},
		{desc: "supports Tailwind CSS v3.4 features", in: "grid-cols-2 grid-cols-subgrid grid-rows-5 grid-rows-subgrid", out: "grid-cols-subgrid grid-rows-subgrid"},
		{desc: "supports Tailwind CSS v3.4 features", in: "min-w-0 min-w-50 min-w-px max-w-0 max-w-50 max-w-px", out: "min-w-px max-w-px"},
		{desc: "supports Tailwind CSS v3.4 features", in: "forced-color-adjust-none forced-color-adjust-auto", out: "forced-color-adjust-auto"},
		{desc: "supports Tailwind CSS v3.4 features", in: "appearance-none appearance-auto", out: "appearance-auto"},
		{desc: "supports Tailwind CSS v3.4 features", in: "float-start float-end clear-start clear-end", out: "float-end clear-end"},
		{desc: "supports Tailwind CSS v3.4 features", in: "*:p-10 *:p-20 hover:*:p-10 hover:*:p-20", out: "*:p-20 hover:*:p-20"},
		{desc: "supports Tailwind CSS v4.0 features", in: "transform-3d transform-flat", out: "transform-flat"},
		{desc: "supports Tailwind CSS v4.0 features", in: "rotate-12 rotate-x-2 rotate-none rotate-y-3", out: "rotate-x-2 rotate-none rotate-y-3"},
		{desc: "supports Tailwind CSS v4.0 features", in: "perspective-dramatic perspective-none perspective-midrange", out: "perspective-midrange"},
		{desc: "supports Tailwind CSS v4.0 features", in: "perspective-origin-center perspective-origin-top-left", out: "perspective-origin-top-left"},
		{desc: "supports Tailwind CSS v4.0 features", in: "bg-linear-to-r bg-linear-45", out: "bg-linear-45"},
		{desc: "supports Tailwind CSS v4.0 features", in: "bg-linear-to-r bg-radial-[something] bg-conic-10", out: "bg-conic-10"},
		{desc: "supports Tailwind CSS v4.0 features", in: "ring-4 ring-orange inset-ring inset-ring-3 inset-ring-blue", out: "ring-4 ring-orange inset-ring-3 inset-ring-blue"},
		{desc: "supports Tailwind CSS v4.0 features", in: "field-sizing-content field-sizing-fixed", out: "field-sizing-fixed"},
		{desc: "supports Tailwind CSS v4.0 features", in: "scheme-normal scheme-dark", out: "scheme-dark"},
		{desc: "supports Tailwind CSS v4.0 features", in: "font-stretch-expanded font-stretch-[66.66%] font-stretch-50%", out: "font-stretch-50%"},
		{desc: "supports Tailwind CSS v4.0 features", in: "col-span-full col-2 row-span-3 row-4", out: "col-2 row-4"},
		{desc: "supports Tailwind CSS v4.1 features", in: "items-baseline items-baseline-last", out: "items-baseline-last"},
		{desc: "supports Tailwind CSS v4.1 features", in: "self-baseline self-baseline-last", out: "self-baseline-last"},
		{desc: "supports Tailwind CSS v4.1 features", in: "place-content-center place-content-end-safe place-content-center-safe", out: "place-content-center-safe"},
		{desc: "supports Tailwind CSS v4.1 features", in: "items-center-safe items-baseline items-end-safe", out: "items-end-safe"},
		{desc: "supports Tailwind CSS v4.1 features", in: "wrap-break-word wrap-normal wrap-anywhere", out: "wrap-anywhere"},
		{desc: "supports Tailwind CSS v4.1 features", in: "text-shadow-none text-shadow-2xl", out: "text-shadow-2xl"},
		{desc: "supports Tailwind CSS v4.1 features", in: "shadow-md shadow-lg/25 text-shadow-md text-shadow-lg/25", out: "shadow-lg/25 text-shadow-lg/25"},
		{desc: "supports Tailwind CSS v4.1 features", in: "drop-shadow-2xl drop-shadow-[shadow:foo]", out: "drop-shadow-[shadow:foo]"},
		{desc: "supports Tailwind CSS v4.1.5 features", in: "h-12 h-lh", out: "h-lh"},
		{desc: "supports Tailwind CSS v4.1.5 features", in: "min-h-12 min-h-lh", out: "min-h-lh"},
		{desc: "supports Tailwind CSS v4.1.5 features", in: "max-h-12 max-h-lh", out: "max-h-lh"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-s-1 inset-s-2", out: "inset-s-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-e-1 inset-e-2", out: "inset-e-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-bs-1 inset-bs-2", out: "inset-bs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-be-1 inset-be-2", out: "inset-be-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "start-1 inset-s-2", out: "inset-s-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-s-1 start-2", out: "start-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "end-1 inset-e-2", out: "inset-e-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-e-1 end-2", out: "end-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-s-1 inset-e-2 inset-bs-3 inset-be-4 inset-0", out: "inset-0"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-0 inset-s-1 inset-bs-1", out: "inset-0 inset-s-1 inset-bs-1"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-y-1 inset-bs-2 inset-be-3", out: "inset-y-1 inset-bs-2 inset-be-3"},
		{desc: "supports Tailwind CSS v4.2 features", in: "top-1 inset-bs-2 bottom-3 inset-be-4", out: "top-1 inset-bs-2 bottom-3 inset-be-4"},
		{desc: "supports Tailwind CSS v4.2 features", in: "pbs-1 pbs-2", out: "pbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "pbe-1 pbe-2", out: "pbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "mbs-1 mbs-2", out: "mbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "mbe-1 mbe-2", out: "mbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "pt-1 pbs-2", out: "pt-1 pbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "pb-1 pbe-2", out: "pb-1 pbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "mt-1 mbs-2", out: "mt-1 mbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "mb-1 mbe-2", out: "mb-1 mbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "p-0 pbs-1 pbe-1", out: "p-0 pbs-1 pbe-1"},
		{desc: "supports Tailwind CSS v4.2 features", in: "pbs-1 pbe-1 p-0", out: "p-0"},
		{desc: "supports Tailwind CSS v4.2 features", in: "m-0 mbs-1 mbe-1", out: "m-0 mbs-1 mbe-1"},
		{desc: "supports Tailwind CSS v4.2 features", in: "mbs-1 mbe-1 m-0", out: "m-0"},
		{desc: "supports Tailwind CSS v4.2 features", in: "py-1 pbs-2 pbe-3", out: "py-1 pbs-2 pbe-3"},
		{desc: "supports Tailwind CSS v4.2 features", in: "my-1 mbs-2 mbe-3", out: "my-1 mbs-2 mbe-3"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-pbs-1 scroll-pbs-2", out: "scroll-pbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-pbe-1 scroll-pbe-2", out: "scroll-pbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-mbs-1 scroll-mbs-2", out: "scroll-mbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-mbe-1 scroll-mbe-2", out: "scroll-mbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-pt-1 scroll-pbs-2", out: "scroll-pt-1 scroll-pbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-pb-1 scroll-pbe-2", out: "scroll-pb-1 scroll-pbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-mt-1 scroll-mbs-2", out: "scroll-mt-1 scroll-mbs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-mb-1 scroll-mbe-2", out: "scroll-mb-1 scroll-mbe-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-p-0 scroll-pbs-1 scroll-pbe-1", out: "scroll-p-0 scroll-pbs-1 scroll-pbe-1"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-pbs-1 scroll-pbe-1 scroll-p-0", out: "scroll-p-0"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-m-0 scroll-mbs-1 scroll-mbe-1", out: "scroll-m-0 scroll-mbs-1 scroll-mbe-1"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-mbs-1 scroll-mbe-1 scroll-m-0", out: "scroll-m-0"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-py-1 scroll-pbs-2 scroll-pbe-3", out: "scroll-py-1 scroll-pbs-2 scroll-pbe-3"},
		{desc: "supports Tailwind CSS v4.2 features", in: "scroll-my-1 scroll-mbs-2 scroll-mbe-3", out: "scroll-my-1 scroll-mbs-2 scroll-mbe-3"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-bs-1 border-bs-2", out: "border-bs-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-be-1 border-be-2", out: "border-be-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-bs-red border-bs-blue", out: "border-bs-blue"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-be-red border-be-blue", out: "border-be-blue"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-2 border-bs-4 border-be-6", out: "border-2 border-bs-4 border-be-6"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-bs-4 border-be-6 border-2", out: "border-2"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-red border-bs-blue border-be-green", out: "border-red border-bs-blue border-be-green"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-bs-blue border-be-green border-red", out: "border-red"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-y-2 border-bs-4 border-be-6", out: "border-y-2 border-bs-4 border-be-6"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-t-2 border-bs-4 border-b-6 border-be-8", out: "border-t-2 border-bs-4 border-b-6 border-be-8"},
		{desc: "supports Tailwind CSS v4.2 features", in: "border-y-red border-bs-blue border-be-green", out: "border-y-red border-bs-blue border-be-green"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inline-1/2 inline-3/4", out: "inline-3/4"},
		{desc: "supports Tailwind CSS v4.2 features", in: "block-1/2 block-3/4", out: "block-3/4"},
		{desc: "supports Tailwind CSS v4.2 features", in: "min-inline-auto min-inline-full", out: "min-inline-full"},
		{desc: "supports Tailwind CSS v4.2 features", in: "max-inline-none max-inline-10", out: "max-inline-10"},
		{desc: "supports Tailwind CSS v4.2 features", in: "min-block-auto min-block-lh min-block-10", out: "min-block-10"},
		{desc: "supports Tailwind CSS v4.2 features", in: "max-block-none max-block-lh max-block-10", out: "max-block-10"},
		{desc: "supports Tailwind CSS v4.2 features", in: "w-10 inline-20", out: "w-10 inline-20"},
		{desc: "supports Tailwind CSS v4.2 features", in: "h-10 block-20", out: "h-10 block-20"},
		{desc: "supports Tailwind CSS v4.2 features", in: "size-10 inline-20 block-30", out: "size-10 inline-20 block-30"},
		{desc: "supports Tailwind CSS v4.2 features", in: "min-w-10 min-inline-20", out: "min-w-10 min-inline-20"},
		{desc: "supports Tailwind CSS v4.2 features", in: "max-h-10 max-block-20", out: "max-h-10 max-block-20"},
		{desc: "supports Tailwind CSS v4.2 features", in: "font-features-[\"smcp\"] font-features-[\"onum\"]", out: "font-features-[\"onum\"]"},
		{desc: "supports Tailwind CSS v4.2 features", in: "font-features-[var(--font-features)] font-features-[\"liga\",\"dlig\"]", out: "font-features-[\"liga\",\"dlig\"]"},
		{desc: "supports Tailwind CSS v4.2 features", in: "tabular-nums font-features-[\"smcp\"]", out: "tabular-nums font-features-[\"smcp\"]"},
		{desc: "supports Tailwind CSS v4.2 features", in: "font-features-[\"smcp\"] normal-nums", out: "font-features-[\"smcp\"] normal-nums"},
		{desc: "supports Tailwind CSS v4.2 features", in: "font-sans font-features-[\"smcp\"]", out: "font-sans font-features-[\"smcp\"]"},
		{desc: "supports Tailwind CSS v4.2 features", in: "aspect-8/11 aspect-8.5/11", out: "aspect-8.5/11"},
		{desc: "supports Tailwind CSS v4.2 features", in: "w-8/11 w-8.5/11", out: "w-8.5/11"},
		{desc: "supports Tailwind CSS v4.2 features", in: "inset-1/2 inset-1.25/2.5", out: "inset-1.25/2.5"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container @container-normal @container-size", out: "@container-size"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container @container-size/sidebar", out: "@container-size/sidebar"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container-normal @container-size/sidebar", out: "@container-size/sidebar"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container-size/sidebar @container", out: "@container-size/sidebar @container"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container/sidebar @container-normal", out: "@container/sidebar @container-normal"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container/sidebar @container-normal/sidebar @container-size/content", out: "@container-size/content"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container/sidebar @container-normal/content @container-size", out: "@container-normal/content @container-size"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container-size @container/sidebar", out: "@container/sidebar"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "hover:@container hover:@container-size/sidebar", out: "hover:@container-size/sidebar"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "hover:@container-size/sidebar hover:@container", out: "hover:@container-size/sidebar hover:@container"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container! @container-size/sidebar!", out: "@container-size/sidebar!"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container-size/sidebar! @container!", out: "@container-size/sidebar! @container!"},
		{desc: "supports Tailwind CSS v4.3 container query container features", in: "@container-foo/sidebar @container-size/sidebar", out: "@container-foo/sidebar @container-size/sidebar"},
		{desc: "supports Tailwind CSS v4.3 scrollbar features", in: "scrollbar-auto scrollbar-thin scrollbar-none", out: "scrollbar-none"},
		{desc: "supports Tailwind CSS v4.3 scrollbar features", in: "scrollbar-gutter-auto scrollbar-gutter-stable scrollbar-gutter-both", out: "scrollbar-gutter-both"},
		{desc: "supports Tailwind CSS v4.3 scrollbar features", in: "scrollbar-thumb-red-500 scrollbar-thumb-blue-500", out: "scrollbar-thumb-blue-500"},
		{desc: "supports Tailwind CSS v4.3 scrollbar features", in: "scrollbar-thumb-red-500 scrollbar-thumb-red-500/50", out: "scrollbar-thumb-red-500/50"},
		{desc: "supports Tailwind CSS v4.3 scrollbar features", in: "scrollbar-track-red-500 scrollbar-track-blue-500", out: "scrollbar-track-blue-500"},
		{desc: "supports Tailwind CSS v4.3 scrollbar features", in: "scrollbar-thin scrollbar-thumb-red-500 scrollbar-track-blue-500", out: "scrollbar-thin scrollbar-thumb-red-500 scrollbar-track-blue-500"},
		{desc: "supports Tailwind CSS v4.3 tab-size features", in: "tab-2 tab-8", out: "tab-8"},
		{desc: "supports Tailwind CSS v4.3 tab-size features", in: "tab-8 tab-[12px]", out: "tab-[12px]"},
		{desc: "supports Tailwind CSS v4.3 tab-size features", in: "tab-4 tabular-nums", out: "tab-4 tabular-nums"},
		{desc: "supports Tailwind CSS v4.3 zoom features", in: "zoom-50 zoom-100", out: "zoom-100"},
		{desc: "supports Tailwind CSS v4.3 zoom features", in: "zoom-50 scale-125", out: "zoom-50 scale-125"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From tw-merge.test.ts
func TestGenerated_TwMerge(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "twMerge", in: "mix-blend-normal mix-blend-multiply", out: "mix-blend-multiply"},
		{desc: "twMerge", in: "h-10 h-min", out: "h-min"},
		{desc: "twMerge", in: "stroke-black stroke-1", out: "stroke-black stroke-1"},
		{desc: "twMerge", in: "stroke-2 stroke-[3]", out: "stroke-[3]"},
		{desc: "twMerge", in: "outline-black outline-1", out: "outline-black outline-1"},
		{desc: "twMerge", in: "grayscale-0 grayscale-[50%]", out: "grayscale-[50%]"},
		{desc: "twMerge", in: "grow grow-[2]", out: "grow-[2]"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

// From wonky-inputs.test.ts
func TestGenerated_WonkyInputs(t *testing.T) {
	tests := []struct {
		desc string
		in   string
		out  string
	}{
		{desc: "handles wonky inputs", in: " block", out: "block"},
		{desc: "handles wonky inputs", in: "block ", out: "block"},
		{desc: "handles wonky inputs", in: " block ", out: "block"},
		{desc: "handles wonky inputs", in: "  block  px-2     py-4  ", out: "block px-2 py-4"},
		{desc: "handles wonky inputs", in: "  block  px-2        py-4  ", out: "block px-2 py-4"},
		{desc: "handles wonky inputs", in: "block\npx-2", out: "block px-2"},
		{desc: "handles wonky inputs", in: "\nblock\npx-2\n", out: "block px-2"},
		{desc: "handles wonky inputs", in: "  block\n        \n        px-2   \n          py-4  ", out: "block px-2 py-4"},
		{desc: "handles wonky inputs", in: "\r  block\n\r        \n        px-2   \n          py-4  ", out: "block px-2 py-4"},
	}
	for _, tc := range tests {
		t.Run(tc.desc+"/"+tc.in, func(t *testing.T) {
			got := Merge(tc.in)
			if got != tc.out {
				t.Errorf("Merge(%q) = %q; want %q", tc.in, got, tc.out)
			}
		})
	}
}

